### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SERVER_ADDR'

### ISSUE THREAD

**Issue by aleperuz** [Cr4sh/MicroBackdoor#5]
hello everyone, I found a problem in the file client_builder.py it says in the Conf module there is no SERVER_ADDR attribut.
But checking in the config.py file there is the variable SERVER_ADDR, I tried to search the internet for the solution but I didn't find anything, I hope you could tell me the solution to this problem.

ERROR:
`python2 client_builder.py client.dll 127.0.0.1
Traceback (most recent call last):
  File "client_builder.py", line 108, in <module>
    exit(main())
  File "client_builder.py", line 85, in main
    addr = Conf.SERVER_ADDR
AttributeError: 'module' object has no attribute 'SERVER_ADDR'
`

**Comment by Cr4sh** [comment]
Sorry, can't reproduce, please check your system configuration.

```
% git clone https://github.com/Cr4sh/MicroBackdoor
Cloning into 'MicroBackdoor'...
remote: Enumerating objects: 309, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 309 (delta 49), reused 33 (delta 33), pack-reused 257
Receiving objects: 100% (309/309), 2.60 MiB | 8.26 MiB/s, done.
Resolving deltas: 100% (163/163), done.
% sudo apt-get install build-essential swig libssl-dev python python-dev python-setuptools python-pip > /dev/null
% sudo pip install m2crypto pycrypto redis cherrypy defusedxml > /dev/null
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/home/user/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag
% cd MicroBackdoor/server
% ./server.py -k

Generating "/home/user/MicroBackdoor/server/server.key" and "/home/user/MicroBackdoor/server/server.crt"
Can't load /home/user/.rnd into RNG
140272329753600:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/user/.rnd
Generating a RSA private key
...........................................................................................................................................................................+++++
...........................................................................................................+++++
writing new private key to '/home/user/MicroBackdoor/server/server.key'
-----

% cd ..
% python client_builder.py client.dll 127.0.0.1
Using server address 127.0.0.1:28115
Using server certificate "/home/user/MicroBackdoor/server/server.crt"
18512 bytes readed from "client.dll"
".conf" section at RVA 0x3e90
18512 bytes written into the "client.dll"
```
